// AGENCIA BEAT 2.0 — conector Supabase multi-sitio
const SUPABASE_URL="https://opnuuhnjdbczevvgtnbw.supabase.co";
const SUPABASE_KEY="sb_publishable__IyI5r0eYrGzS7amcaGapg_AUZR9KbE";
const PORTAL=window.PORTAL_CONFIG||{};
const SITIO_ID=PORTAL.sitioId||"agenciabeat";
const NOTICIAS_POR_PAGINA=PORTAL.noticiasPorPagina||10;
let paginaActual=1,categoriaActual=null,totalNoticias=0,configPortal={};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path,extra={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,...extra}});if(!r.ok)throw new Error(`Supabase ${r.status}`);return r}
async function obtenerConfiguracion(){try{const r=await api(`config?sitio_id=eq.${encodeURIComponent(SITIO_ID)}`);const d=await r.json();configPortal=d[0]||{};return configPortal}catch(e){console.warn("Configuración por defecto",e);return{}}}
async function obtenerNoticias(pagina=1,categoria=null){const desde=(pagina-1)*NOTICIAS_POR_PAGINA,hasta=desde+NOTICIAS_POR_PAGINA-1;let q=`noticias?select=*&sitio_id=eq.${encodeURIComponent(SITIO_ID)}&order=created_at.desc`;if(categoria)q+=`&categoria=eq.${encodeURIComponent(categoria.toLowerCase().trim())}`;const r=await api(q,{Range:`${desde}-${hasta}`,Prefer:"count=exact"});const d=await r.json(),range=r.headers.get("content-range");totalNoticias=range?parseInt(range.split("/")[1]):d.length;return d}
async function obtenerNoticiasMultimedia(limite=60){const r=await api(`noticias?select=id,titulo,categoria,imagen_url,created_at&sitio_id=eq.${encodeURIComponent(SITIO_ID)}&order=created_at.desc&limit=${Math.max(1,Math.min(100,limite))}`);const rows=await r.json();return window.BeatEditorial?window.BeatEditorial.apply(rows):rows}
async function obtenerNoticiaPorId(id){const r=await api(`noticias?select=*&id=eq.${encodeURIComponent(id)}&sitio_id=eq.${encodeURIComponent(SITIO_ID)}`);return(await r.json())[0]||null}
const fechaCorta=v=>new Date(v).toLocaleDateString("es-AR",{day:"numeric",month:"short",year:"numeric"});
function renderizarNoticias(ns){const c=document.getElementById("bloqueNoticias");if(!c)return;if(!ns?.length){c.innerHTML='<p class="cargando">No hay noticias publicadas en esta sección.</p>';return}c.innerHTML=ns.map(n=>{const resumen=(n.contenido||"").replace(/<[^>]*>/g,"").slice(0,155);return `<article class="tarjeta-noticia"><a href="noticia.html?id=${encodeURIComponent(n.id)}"><img src="${esc(n.imagen_url||'https://placehold.co/800x450?text=Agencia+Beat')}" alt="${esc(n.titulo)}" loading="lazy"></a><div class="tarjeta-body"><span class="categoria">${esc(n.categoria||'General')}</span><h2><a href="noticia.html?id=${encodeURIComponent(n.id)}">${esc(n.titulo)}</a></h2><p class="resumen">${esc(resumen)}${resumen?'…':''}</p><span class="fecha">${fechaCorta(n.created_at)}</span></div></article>`}).join("")}
async function renderizarDestacados(){const c=document.getElementById("destacadoPrincipal");if(!c)return;let ds=Array.isArray(configPortal.destacados)?configPortal.destacados:[];if(!ds.length){try{ds=await obtenerNoticias(1,null)}catch{ds=[]}}if(!ds.length){c.innerHTML='<div class="destacado-item principal"><p>No hay noticias disponibles.</p></div>';return}const p=ds[0],sec=ds.slice(1,4);c.innerHTML=`<div class="destacado-item principal"><a href="noticia.html?id=${encodeURIComponent(p.id)}"><img src="${esc(p.imagen_url||'https://placehold.co/1200x675?text=Agencia+Beat')}" alt="${esc(p.titulo)}"><span class="categoria">${esc(p.categoria||'Actualidad')}</span><h2>${esc(p.titulo)}</h2></a></div><div class="destacado-item secundario">${sec.map(s=>`<h3><a href="noticia.html?id=${encodeURIComponent(s.id)}">${esc(s.titulo)}</a></h3><span class="fecha">${fechaCorta(s.created_at)}</span>`).join("")}</div>`}
function renderizarSidebar(){const c=document.getElementById("barraLateral");if(!c)return;c.innerHTML=`<div class="widget"><span class="eyebrow">RED FEDERAL</span><h3>Agencia Beat</h3><p>Una central editorial preparada para distribuir información a múltiples diarios y plataformas.</p></div><div class="widget widget-popular"><h3>Últimas noticias</h3><ul id="listaMasLeidas"><li>Cargando...</li></ul></div><div class="adbox">PUBLICIDAD PATROCINADA</div>`;cargarMasLeidas()}
async function cargarMasLeidas(){try{const ns=await obtenerNoticias(1,null),l=document.getElementById("listaMasLeidas");if(l)l.innerHTML=ns.slice(0,5).map(n=>`<li><a href="noticia.html?id=${encodeURIComponent(n.id)}">${esc(n.titulo)}</a></li>`).join("")}catch(e){console.warn(e)}}
function actualizarPaginacion(){const t=Math.max(1,Math.ceil(totalNoticias/NOTICIAS_POR_PAGINA)),a=document.getElementById("btnAnterior"),s=document.getElementById("btnSiguiente"),c=document.getElementById("controlPaginas");if(c)c.textContent=`Página ${paginaActual} de ${t}`;if(a)a.disabled=paginaActual<=1;if(s)s.disabled=paginaActual>=t}
async function cargarNoticias(){const c=document.getElementById("bloqueNoticias");if(!c)return;c.innerHTML='<p class="cargando">Cargando noticias...</p>';try{renderizarNoticias(await obtenerNoticias(paginaActual,categoriaActual));actualizarPaginacion();const h=document.getElementById("nombreSeccion");if(h)h.textContent=categoriaActual?categoriaActual.replaceAll("-"," "):"Últimas noticias"}catch(e){console.error(e);c.innerHTML='<p class="cargando">No se pudieron cargar las noticias.</p>'}}
async function renderizarNoticiaCompleta(){const id=new URLSearchParams(location.search).get("id"),a=document.getElementById("noticiaCompleta");if(!id||!a)return;try{const n=await obtenerNoticiaPorId(id);if(!n){a.innerHTML='<p>Noticia no encontrada.</p>';return}document.title=`${n.titulo} — Agencia Beat`;document.getElementById("categoriaNoticia").textContent=n.categoria||"General";document.getElementById("tituloNoticiaContenido").textContent=n.titulo;document.getElementById("fechaNoticia").textContent=new Date(n.created_at).toLocaleDateString("es-AR",{day:"numeric",month:"long",year:"numeric"});document.getElementById("imagenNoticia").innerHTML=n.imagen_url?`<img src="${esc(n.imagen_url)}" alt="${esc(n.titulo)}">`:"";document.getElementById("cuerpoNoticia").innerHTML=n.contenido||"<p>Contenido no disponible.</p>";document.querySelectorAll("[data-share]").forEach(b=>b.onclick=()=>compartir(b.dataset.share,n.titulo))}catch(e){console.error(e);a.innerHTML='<p>Error al cargar la noticia.</p>'}}
async function compartir(tipo,titulo){const url=location.href,text=`${titulo} — Agencia Beat`;if(tipo==="native"&&navigator.share){await navigator.share({title:titulo,text,url});return}const target=tipo==="x"?`https://x.com/intent/post?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`:tipo==="bluesky"?`https://bsky.app/intent/compose?text=${encodeURIComponent(text+' '+url)}`:"";if(target)window.open(target,"_blank","noopener,noreferrer")}
async function init(){await obtenerConfiguracion();const f=document.getElementById("fechaActual");if(f)f.textContent=new Date().toLocaleDateString("es-AR",{weekday:"long",day:"numeric",month:"long",year:"numeric"});if(document.getElementById("noticiaCompleta")){renderizarNoticiaCompleta();return}const cat=new URLSearchParams(location.search).get("cat");if(cat)categoriaActual=cat;await renderizarDestacados();renderizarSidebar();document.getElementById("btnAnterior")?.addEventListener("click",()=>{if(paginaActual>1){paginaActual--;cargarNoticias();scrollTo({top:0,behavior:"smooth"})}});document.getElementById("btnSiguiente")?.addEventListener("click",()=>{paginaActual++;cargarNoticias();scrollTo({top:0,behavior:"smooth"})});cargarNoticias()}
if(!document.body.classList.contains('mm-body'))document.addEventListener("DOMContentLoaded",init);