(()=>{const CFG=window.PORTAL_CONFIG||{sitioId:'agenciabeat',nombre:'AGENCIA BEAT',slogan:'La noticia hoy',color:'#004290'};let noticias=[],actual=null,formato='45';const $=s=>document.querySelector(s),canvas=$('#placa'),ctx=canvas.getContext('2d');
async function cargar(){try{noticias=await obtenerNoticiasMultimedia();pintarLista(noticias)}catch(e){$('#listaNoticias').innerHTML='<p>No se pudieron cargar noticias.</p>';console.error(e)}}
function pintarLista(arr){$('#listaNoticias').innerHTML=arr.map(n=>`<div class="mm-item" data-id="${n.id}"><b>${esc(n.titulo)}</b><span>${esc(n.categoria||'General')} · ${new Date(n.created_at).toLocaleDateString('es-AR')}</span></div>`).join('')||'<p>Sin noticias.</p>'}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#buscar').addEventListener('input',e=>{const q=e.target.value.toLowerCase();pintarLista(noticias.filter(n=>(n.titulo+' '+(n.categoria||'')).toLowerCase().includes(q))) });
$('#listaNoticias').addEventListener('click',e=>{const item=e.target.closest('.mm-item');if(!item)return;actual=noticias.find(n=>String(n.id)===item.dataset.id);document.querySelectorAll('.mm-item').forEach(x=>x.classList.remove('activo'));item.classList.add('activo');$('#editorVacio').hidden=true;$('#editor').hidden=false;$('#tituloEdit').value=actual.titulo||'';$('#categoriaEdit').value=actual.categoria||'Actualidad';$('#imagenEdit').value=actual.imagen_url||'';generar()});
['tituloEdit','categoriaEdit','imagenEdit'].forEach(id=>$('#'+id).addEventListener('change',generar));document.querySelectorAll('[data-format]').forEach(b=>b.addEventListener('click',()=>{formato=b.dataset.format;document.querySelectorAll('[data-format]').forEach(x=>x.classList.toggle('activo',x===b));generar()}));$('#regenerar').onclick=generar;$('#descargar').onclick=()=>{const a=document.createElement('a');a.download=`agencia-beat-${formato==='45'?'4x5':'9x16'}-${actual?.id||'placa'}.png`;a.href=canvas.toDataURL('image/png');a.click()};
function img(url){return new Promise((ok,no)=>{if(!url)return no();const im=new Image();im.crossOrigin='anonymous';im.onload=()=>ok(im);im.onerror=no;im.src=url})}
function cover(im,w,h){const r=Math.max(w/im.width,h/im.height),sw=w/r,sh=h/r,sx=(im.width-sw)/2,sy=(im.height-sh)/2;ctx.drawImage(im,sx,sy,sw,sh,0,0,w,h)}
function wrap(text,maxWidth,maxLines,fontStart,fontMin){let size=fontStart,lines=[];while(size>=fontMin){ctx.font=`900 ${size}px Arial`;const words=text.trim().split(/\s+/);lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width<=maxWidth)line=test;else{if(line)lines.push(line);line=word}}if(line)lines.push(line);if(lines.length<=maxLines)break;size-=2}if(lines.length>maxLines){lines=lines.slice(0,maxLines);let last=lines[maxLines-1];while(ctx.measureText(last+'…').width>maxWidth&&last.includes(' '))last=last.slice(0,last.lastIndexOf(' '));lines[maxLines-1]=last+'…'}return{size,lines,lineHeight:size*1.08}}
async function generar(){if(!actual)return;const w=1080,h=formato==='45'?1350:1920;canvas.width=w;canvas.height=h;ctx.fillStyle='#071b35';ctx.fillRect(0,0,w,h);try{cover(await img($('#imagenEdit').value.trim()),w,h)}catch{}const g=ctx.createLinearGradient(0,h*.28,0,h);g.addColorStop(0,'rgba(0,18,45,0)');g.addColorStop(.55,'rgba(0,18,45,.58)');g.addColorStop(1,'rgba(0,18,45,.98)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle=CFG.color||'#004290';ctx.lineWidth=formato==='45'?24:28;ctx.strokeRect(12,12,w-24,h-24);const cy=formato==='45'?650:1030,cat=($('#categoriaEdit').value||'ACTUALIDAD').toUpperCase();ctx.fillStyle=CFG.color||'#004290';ctx.fillRect(70,cy,Math.min(390,cat.length*23+70),54);ctx.fillStyle='#fff';ctx.font='800 25px Arial';ctx.textAlign='left';ctx.fillText(cat,92,cy+36);const fit=wrap($('#tituloEdit').value.trim(),920,formato==='45'?5:7,formato==='45'?72:78,46);ctx.font=`900 ${fit.size}px Arial`;ctx.fillStyle='#fff';ctx.textAlign='center';const start=formato==='45'?760:1150;fit.lines.forEach((l,i)=>ctx.fillText(l,w/2,start+i*fit.lineHeight));const by=h-115;ctx.font='900 43px Arial';ctx.fillStyle='#fff';ctx.fillText('AGENCIA BEAT',w/2,by);ctx.font='600 22px Arial';ctx.fillStyle='rgba(255,255,255,.82)';ctx.fillText((CFG.slogan||'La noticia hoy').toUpperCase(),w/2,by+42);$('#estado').textContent=`Lista: ${w} × ${h} px · ${fit.lines.length} líneas de titular.`}
cargar()})();