'use strict';
const API='https://beat-editorial-preview.beatdigitalok-bac.workers.dev';
const $=id=>document.getElementById(id);let current=null,busy=false,rowsCache=[],pendingSource=null;
const access=window.BeatPreviewAccess;
function forget(){access.clear();$('token').value='';rowsCache=[];renderList();$('accessPanel').open=true;}
$('token').value=access.read();
window.addEventListener('storage',()=>{$('token').value=access.read();if(!$('token').value){edit(null);$('list').replaceChildren();}});
$('logout').onclick=()=>{forget();edit(null);$('list').replaceChildren();$('msg').textContent='Sesión cerrada';};
async function api(path,body){const token=$('token').value;if(token.length<32)throw Error('Ingresá el token editorial de al menos 32 caracteres.');const r=await fetch(API+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+token,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(r.status===401)forget();if(!r.ok)throw Error(data.message||data.error||'Error '+r.status);access.remember(token);return data;}
async function run(fn){if(busy)return;busy=true;try{await fn();}catch(e){$('msg').textContent=e.message;}finally{busy=false;}}
function edit(row){current=row;pendingSource=null;showSource(row?.fuentes?.[0]);$('editorHeading').textContent=row?'Editar noticia':'Nueva noticia';$('form').reset();for(const key of ['titulo','bajada','contenido','categoria','imagen_url','imagen_tipo','estado'])$(key).value=row?.[key]??(key==='categoria'?'informacion general':key==='estado'?'borrador':key==='imagen_tipo'?'sin_imagen':'');$('msg').textContent=row?'Editando revisión '+row.revision:'Nueva noticia';updatePreview();}
function renderList(){const query=$('newsSearch').value.trim().toLocaleLowerCase('es'),state=$('newsState').value;const rows=rowsCache.filter(row=>(row.titulo+' '+row.categoria).toLocaleLowerCase('es').includes(query)&&(state==='trash'?!!row.deleted_at:!row.deleted_at&&(state==='all'||row.estado===state)));$('newsCount').textContent=rows.length+' noticias en esta vista';$('list').replaceChildren();for(const row of rows){const article=document.createElement('article'),title=document.createElement('p');title.textContent=row.titulo+' · '+(row.deleted_at?'Papelera':row.estado);article.append(title);const button=document.createElement('button');button.textContent='Editar';button.onclick=()=>edit(row);article.append(button);const view=document.createElement('a');view.textContent='Ver noticia';view.href='noticia-propia-preview.html?id='+encodeURIComponent(row.id);article.append(view);if(!row.deleted_at){const pub=document.createElement('button');pub.textContent=row.estado==='publicado'?'Retirar de preview':'Publicar en preview';pub.onclick=()=>run(async()=>{await api('/api/manual/change',{id:row.id,expected_revision:row.revision,action:'edit',fields:{estado:row.estado==='publicado'?'borrador':'publicado'}});await load();if(current?.id===row.id)edit(null);$('msg').textContent='Estado actualizado en la web de prueba';});article.append(pub);}const trash=document.createElement('button');trash.textContent=row.deleted_at?'Restaurar':'Enviar a papelera';trash.onclick=()=>run(async()=>{await api('/api/manual/change',{id:row.id,expected_revision:row.revision,action:row.deleted_at?'restore':'trash'});await load();if(current?.id===row.id)edit(null);$('msg').textContent='Cambio guardado';});article.append(trash);$('list').append(article);}if(!rows.length){const p=document.createElement('p');p.className='empty';p.textContent='No hay noticias en esta vista.';$('list').append(p);}}async function load(){const data=await api('/api/manual/list');rowsCache=data.rows;renderList();return rowsCache.length;}
$('load').onclick=()=>run(async()=>{$('msg').textContent=(await load())+' borradores cargados';});$('new').onclick=()=>edit(null);
$('form').onsubmit=e=>{e.preventDefault();run(async()=>{const fields={};for(const key of ['titulo','bajada','contenido','categoria','imagen_url','imagen_tipo','estado'])fields[key]=$(key).value;if(!fields.imagen_url)fields.imagen_tipo='sin_imagen';else if(fields.imagen_tipo==='sin_imagen')fields.imagen_tipo='foto';const result=await api(current?'/api/manual/change':'/api/manual/create',current?{id:current.id,expected_revision:current.revision,action:'edit',fields}:{fields,...(pendingSource?{source:pendingSource}:{})});edit(result.row);await load();$('msg').textContent='Guardado en Supabase preview · revisión '+result.row.revision;});};

let aiDraft=null;
$('aiGenerate').onclick=()=>run(async()=>{const button=$('aiGenerate');button.disabled=true;$('msg').textContent='Generando propuesta…';try{const result=await api('/api/manual/generate',{material:$('aiMaterial').value,provider:$('aiProvider').value});aiDraft=result.draft;$('aiProposal').textContent=aiDraft.titulo+'\n\n'+aiDraft.bajada+'\n\n'+aiDraft.contenido;$('aiPending').textContent='Datos a revisar: '+(aiDraft.pendientes.join('; ')||'Verificá la propuesta contra tus fuentes.');$('aiImage').value=aiDraft.prompt_imagen;$('aiReview').hidden=false;$('msg').textContent='Propuesta generada. Todavía no está guardada ni publicada.';}finally{button.disabled=false;}});
$('aiApply').onclick=()=>{if(!aiDraft)return;for(const key of ['titulo','bajada','contenido'])$(key).value=aiDraft[key];$('estado').value='borrador';updatePreview();$('msg').textContent='Propuesta aplicada. Revisá los datos y guardá cuando esté lista.';};


$('newsSearch').oninput=renderList;$('newsState').onchange=renderList;$('newTop').onclick=()=>{edit(null);$('titulo').focus();};if(!access.read())$('accessPanel').open=true;else run(async()=>{await load();$('msg').textContent='Noticias cargadas. Elegí una o comenzá una nueva.';});

function updatePreview(){ $('livePreviewTitle').textContent=$('titulo').value||'Tu próximo titular';$('livePreviewCategory').textContent=$('categoria').value||'Información general';const im=$('livePreviewImage');let url='';try{const u=new URL($('imagen_url').value);if(u.protocol==='https:'&&!u.username&&!u.password)url=u.href;}catch{}im.hidden=!url;if(url&&im.getAttribute('src')!==url)im.src=url;if(!url)im.removeAttribute('src');}['titulo','categoria','imagen_url'].forEach(id=>$(id).addEventListener('input',updatePreview));$('livePreviewImage').onerror=()=>{$('livePreviewImage').hidden=true;};$('studio').ontoggle=()=>{if($('studio').open&&!$('studioFrame').getAttribute('src'))$('studioFrame').src=$('studioFrame').dataset.src;};$('openStudio').onclick=()=>{$('studio').open=true;};updatePreview();

$('useEditorText').onclick=()=>{$('aiMaterial').value=[$('titulo').value,$('bajada').value,$('contenido').value].filter(Boolean).join('\n\n');$('aiMaterial').focus();$('msg').textContent='Texto copiado como base. Elegí el motor y generá una propuesta para revisar.';};

function showSource(source){const el=$('sourceInfo');el.replaceChildren();if(!source?.url)return;const text=document.createElement('span');text.textContent='Fuente original: ';const link=document.createElement('a');link.textContent=source.title||source.titulo_original||source.url;link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';el.append(text,link);}
function rssText(value){const stripped=String(value||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<[^>]*>/g,' ');const el=document.createElement('textarea');el.innerHTML=stripped;return el.value.replace(/\s+/g,' ').trim();}
function safeRSSLink(value,base){if(!value||!String(value).trim())return '';try{const u=new URL(value,base);if(u.protocol!=='https:'||u.username||u.password)return '';u.hash='';for(const key of [...u.searchParams.keys()])if(/^utm_/i.test(key)||['fbclid','gclid'].includes(key))u.searchParams.delete(key);u.searchParams.sort();return u.href;}catch{return '';}}
function parseRSS(xml,feed){if(/<!DOCTYPE|<!ENTITY/i.test(xml))throw Error('XML no admitido');const doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw Error('RSS/Atom inválido');const nodes=[...doc.getElementsByTagNameNS('*','item'),...doc.getElementsByTagNameNS('*','entry')];if(!nodes.length)throw Error('El feed no contiene entradas RSS/Atom');const seen=new Set();return nodes.slice(0,80).map(n=>{const elements=name=>[...n.getElementsByTagNameNS('*',name)],text=name=>elements(name)[0]?.textContent||'';const linkNode=elements('link').find(e=>!e.getAttribute('rel')||e.getAttribute('rel')==='alternate');const url=safeRSSLink(linkNode?.getAttribute('href')||linkNode?.textContent||text('guid'),feed);const title=rssText(text('title')).slice(0,1000);const body=rssText(text('encoded')||text('content')||text('description')||text('summary')).slice(0,25000);const imageNode=[...elements('enclosure'),...elements('thumbnail'),...elements('content')].find(e=>(e.getAttribute('type')||'').startsWith('image/')||e.localName==='thumbnail'||e.getAttribute('medium')==='image');const image=safeRSSLink(imageNode?.getAttribute('url')||'',feed);return {url,title,body,image,feed_url:feed};}).filter(n=>{if(!n.url||!n.title||seen.has(n.url))return false;seen.add(n.url);return true;}).slice(0,40);}
const feedKey='beat-rss-sources-preview-v1';let savedFeeds=[];try{const value=JSON.parse(localStorage.getItem(feedKey)||'[]');if(Array.isArray(value))savedFeeds=value.filter(v=>typeof v.url==='string'&&typeof v.category==='string').slice(0,20);}catch{}
function renderFeeds(){const select=$('rssSaved');select.replaceChildren(new Option('Elegir fuente',''));for(const item of savedFeeds)select.add(new Option(item.url,item.url));}
renderFeeds();$('rssSaved').onchange=()=>{const source=savedFeeds.find(s=>s.url===$('rssSaved').value);if(source){$('rssURL').value=source.url;$('rssCategory').value=source.category;}};
$('rssRemember').onclick=()=>{const url=safeRSSLink($('rssURL').value);if(!url){$('rssStatus').textContent='Ingresá una URL HTTPS válida';return;}savedFeeds=[{url,category:$('rssCategory').value.trim()||'informacion general'},...savedFeeds.filter(s=>s.url!==url)].slice(0,20);try{localStorage.setItem(feedKey,JSON.stringify(savedFeeds));renderFeeds();$('rssStatus').textContent='Fuente guardada en este navegador';}catch{$('rssStatus').textContent='El navegador no permitió guardar la fuente';}};
$('rssFetch').onclick=()=>run(async()=>{const button=$('rssFetch');button.disabled=true;$('rssStatus').textContent='Consultando fuente…';try{const data=await api('/api/rss/fetch',{url:$('rssURL').value.trim()});const items=parseRSS(data.xml,data.feed_url);$('rssItems').replaceChildren();for(const item of items){const article=document.createElement('article'),title=document.createElement('p'),summary=document.createElement('p'),button=document.createElement('button');title.textContent=item.title;summary.textContent=item.body.slice(0,250)||'La fuente sólo entregó el título. Completá los datos antes de generar.';button.textContent='Preparar reescritura';button.onclick=()=>{edit(null);pendingSource={url:item.url,feed_url:item.feed_url,title:item.title};showSource(pendingSource);$('titulo').value=item.title;$('categoria').value=$('rssCategory').value.trim()||'informacion general';$('imagen_url').value=item.image;$('imagen_tipo').value=item.image?'foto':'sin_imagen';$('contenido').value=item.body;$('estado').value='borrador';$('aiMaterial').value='FUENTE ORIGINAL: '+item.url+'\nTÍTULO: '+item.title+'\nCONTENIDO DEL RSS: '+item.body;aiDraft=null;$('aiReview').hidden=true;$('aiPanel').open=true;updatePreview();$('aiPanel').scrollIntoView({behavior:'smooth',block:'start'});$('msg').textContent='Fuente cargada. Elegí Groq o Gemini y generá una propuesta. Al guardar se conservará el origen y se creará un borrador.';};article.append(title,summary,button);$('rssItems').append(article);}$('rssStatus').textContent=items.length+' entradas disponibles. Las fuentes guardadas no se consultan automáticamente.';}catch(e){$('rssStatus').textContent=e.message;}finally{button.disabled=false;}});
$('openRSS').onclick=()=>{$('rssPanel').open=true;};
