'use strict';
const API='https://beat-editorial-preview.beatdigitalok-bac.workers.dev';
const $=id=>document.getElementById(id);let current=null,busy=false,rowsCache=[];
const access=window.BeatPreviewAccess;
function forget(){access.clear();$('token').value='';rowsCache=[];renderList();$('accessPanel').open=true;}
$('token').value=access.read();
window.addEventListener('storage',()=>{$('token').value=access.read();if(!$('token').value){edit(null);$('list').replaceChildren();}});
$('logout').onclick=()=>{forget();edit(null);$('list').replaceChildren();$('msg').textContent='Sesión cerrada';};
async function api(path,body){const token=$('token').value;if(token.length<32)throw Error('Ingresá el token editorial de al menos 32 caracteres.');const r=await fetch(API+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+token,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(r.status===401)forget();if(!r.ok)throw Error(data.message||data.error||'Error '+r.status);access.remember(token);return data;}
async function run(fn){if(busy)return;busy=true;try{await fn();}catch(e){$('msg').textContent=e.message;}finally{busy=false;}}
function edit(row){current=row;$('editorHeading').textContent=row?'Editar noticia':'Nueva noticia';$('form').reset();for(const key of ['titulo','bajada','contenido','categoria','imagen_url','imagen_tipo','estado'])$(key).value=row?.[key]??(key==='categoria'?'informacion general':key==='estado'?'borrador':key==='imagen_tipo'?'sin_imagen':'');$('msg').textContent=row?'Editando revisión '+row.revision:'Nueva noticia';}
function renderList(){const query=$('newsSearch').value.trim().toLocaleLowerCase('es'),state=$('newsState').value;const rows=rowsCache.filter(row=>(row.titulo+' '+row.categoria).toLocaleLowerCase('es').includes(query)&&(state==='trash'?!!row.deleted_at:!row.deleted_at&&(state==='all'||row.estado===state)));$('newsCount').textContent=rows.length+' noticias en esta vista';$('list').replaceChildren();for(const row of rows){const article=document.createElement('article'),title=document.createElement('p');title.textContent=row.titulo+' · '+(row.deleted_at?'Papelera':row.estado);article.append(title);const button=document.createElement('button');button.textContent='Editar';button.onclick=()=>edit(row);article.append(button);const view=document.createElement('a');view.textContent='Ver noticia';view.href='noticia-propia-preview.html?id='+encodeURIComponent(row.id);article.append(view);if(!row.deleted_at){const pub=document.createElement('button');pub.textContent=row.estado==='publicado'?'Retirar de preview':'Publicar en preview';pub.onclick=()=>run(async()=>{await api('/api/manual/change',{id:row.id,expected_revision:row.revision,action:'edit',fields:{estado:row.estado==='publicado'?'borrador':'publicado'}});await load();if(current?.id===row.id)edit(null);$('msg').textContent='Estado actualizado en la web de prueba';});article.append(pub);}const trash=document.createElement('button');trash.textContent=row.deleted_at?'Restaurar':'Enviar a papelera';trash.onclick=()=>run(async()=>{await api('/api/manual/change',{id:row.id,expected_revision:row.revision,action:row.deleted_at?'restore':'trash'});await load();if(current?.id===row.id)edit(null);$('msg').textContent='Cambio guardado';});article.append(trash);$('list').append(article);}if(!rows.length){const p=document.createElement('p');p.className='empty';p.textContent='No hay noticias en esta vista.';$('list').append(p);}}async function load(){const data=await api('/api/manual/list');rowsCache=data.rows;renderList();return rowsCache.length;}
$('load').onclick=()=>run(async()=>{$('msg').textContent=(await load())+' borradores cargados';});$('new').onclick=()=>edit(null);
$('form').onsubmit=e=>{e.preventDefault();run(async()=>{const fields={};for(const key of ['titulo','bajada','contenido','categoria','imagen_url','imagen_tipo','estado'])fields[key]=$(key).value;if(!fields.imagen_url)fields.imagen_tipo='sin_imagen';else if(fields.imagen_tipo==='sin_imagen')fields.imagen_tipo='foto';const result=await api(current?'/api/manual/change':'/api/manual/create',current?{id:current.id,expected_revision:current.revision,action:'edit',fields}:{fields});edit(result.row);await load();$('msg').textContent='Guardado en Supabase preview · revisión '+result.row.revision;});};

let aiDraft=null;
$('aiGenerate').onclick=()=>run(async()=>{const button=$('aiGenerate');button.disabled=true;$('msg').textContent='Generando propuesta…';try{const result=await api('/api/manual/generate',{material:$('aiMaterial').value});aiDraft=result.draft;$('aiProposal').textContent=aiDraft.titulo+'\n\n'+aiDraft.bajada+'\n\n'+aiDraft.contenido;$('aiPending').textContent='Datos a revisar: '+(aiDraft.pendientes.join('; ')||'Verificá la propuesta contra tus fuentes.');$('aiImage').value=aiDraft.prompt_imagen;$('aiReview').hidden=false;$('msg').textContent='Propuesta generada. Todavía no está guardada ni publicada.';}finally{button.disabled=false;}});
$('aiApply').onclick=()=>{if(!aiDraft)return;for(const key of ['titulo','bajada','contenido'])$(key).value=aiDraft[key];$('estado').value='borrador';$('msg').textContent='Propuesta aplicada. Revisá los datos y guardá cuando esté lista.';};


$('newsSearch').oninput=renderList;$('newsState').onchange=renderList;$('newTop').onclick=()=>{edit(null);$('titulo').focus();};if(!access.read())$('accessPanel').open=true;else run(async()=>{await load();$('msg').textContent='Noticias cargadas. Elegí una o comenzá una nueva.';});
