import test from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {normalizePost,validateOverrides,effective,visible} from './core.mjs';
import worker,{databaseUrl} from './worker.mjs';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const post={id:'200',blog:{id:'100'},title:'Título corregido',content:'<p>Noticia</p><img src="https://media.c5n.com/a.jpg">',labels:['Deportes'],status:'LIVE',updated:'2026-10-06T10:00:00Z'};
const env={ENVIRONMENT:'preview',EDITORIAL_ADMIN_TOKEN:'test-token-abcdefghijklmnopqrstuvwxyz',BLOGGER_BLOG_ID:'100'};
const request=(path,body,authorized=true)=>new Request('https://example.test'+path,{method:'POST',headers:{'content-type':'application/json',...(authorized?{authorization:'Bearer '+env.EDITORIAL_ADMIN_TOKEN}:{})},body:JSON.stringify(body)});
test('Blogger corregido: identidad exacta, categoría y estado',()=>{const n=normalizePost(post,'100');assert.equal(n.categoria,'deportes');assert.equal(n.estado,'publicado');assert.equal(n.blogger_post_id,'200');assert.equal(n.imagen_url,'https://media.c5n.com/a.jpg');});
test('Borradores y programados no públicos',()=>{for(const status of ['DRAFT','SCHEDULED'])assert.equal(visible({source:normalizePost({...post,status},'100')}),false);});
test('Sin ADMIN status no se infiere publicado; blog ajeno rechazado',()=>{assert.throws(()=>normalizePost({...post,status:undefined},'100'));assert.throws(()=>normalizePost(post,'999'));});
test('Múltiples categorías van a revisión, sin tomar categoría RSS a ciegas',()=>{const n=normalizePost({...post,labels:['política','Deportes']},'100');assert.equal(n.requiere_revision_categoria,true);});
test('Edición local prevalece, tombstone impide visibilidad',()=>{const r={source:normalizePost(post,'100'),overrides:{categoria:'espectaculos'},deleted_at:'2026-10-06T11:00:00Z',revision:3};assert.equal(effective(r).categoria,'espectaculos');assert.equal(visible(r),false);});
test('No permite editar identidad/estado ni imagen insegura',()=>{assert.throws(()=>validateOverrides({estado:'publicado'}));assert.throws(()=>validateOverrides({imagen_url:'javascript:alert(1)'}));assert.throws(()=>validateOverrides({titulo:''}));});
test('Proyecto actual bloqueado',()=>{assert.throws(()=>databaseUrl({SUPABASE_PREVIEW_URL:'https://opnuuhnjdbczevvgtnbw.supabase.co'}));assert.throws(()=>databaseUrl({SUPABASE_PREVIEW_URL:'https://evil.test'}));});
test('Validación dry-run no toca red ni base',async()=>{const original=globalThis.fetch;globalThis.fetch=()=>{throw Error('No debe acceder a red')};try{const r=await worker.fetch(request('/api/editorial/validate',{post}),env);assert.equal(r.status,200);assert.equal((await r.json()).dry_run,true);}finally{globalThis.fetch=original}});
test('Sin auth / origen ajeno / producción desactivada',async()=>{assert.equal((await worker.fetch(request('/api/editorial/validate',{post},false),env)).status,401);const r=request('/api/editorial/validate',{post});r.headers.set('origin','https://otro.test');assert.equal((await worker.fetch(r,env)).status,403);assert.equal((await worker.fetch(request('/api/editorial/validate',{post}),{...env,ENVIRONMENT:'production'})).status,503);});
test('No guarda edición con escrituras desactivadas',async()=>{const r=await worker.fetch(request('/api/editorial/change',{action:'edit',post_id:'200',expected_revision:1,fields:{categoria:'deportes'}}),env);assert.equal(r.status,403)});
test('Sincronización real hace sólo GET Blogger y devuelve dry-run',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.ok(url.includes('/posts/200?view=ADMIN'));assert.equal(options.method,undefined);return Response.json(post)};try{const r=await worker.fetch(request('/api/editorial/sync',{post_id:'200'}),{...env,BLOGGER_ACCESS_TOKEN:'test'});assert.equal(r.status,200);assert.equal((await r.json()).dry_run,true);assert.equal(calls,1);}finally{globalThis.fetch=original}});
